name: rtd38
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - rasterio==1.2
  - python=3.12.7
  - torch=2.5.1
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - black==20.8b1